package com.notif.api.core.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCodes {
    // Generic
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),

    // Auth
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    ACCOUNT_DISABLED("ACCOUNT_DISABLED"),
    ACCOUNT_LOCKED("ACCOUNT_LOCKED"),
    PASSWORD_EXPIRED("PASSWORD_EXPIRED"),
    AUTHENTICATION_FAILED("AUTHENTICATION_FAILED"),

    // User
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
    INVALID_TOKEN("INVALID_TOKEN"),
    TOKEN_EXPIRED("TOKEN_EXPIRED"),

    // Validation
    VALIDATION_FAILED("VALIDATION_FAILED"),
    NO_FIELDS_TO_UPDATE("NO_FIELDS_TO_UPDATE");


    private final String value;
}