package com.notif.api.core.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode {
    // CORE MODULE
    // System
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),
    CONFIGURATION_ERROR("CONFIGURATION_ERROR"),
    // NotFound
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    // Conflict
    RESOURCE_CONFLICT("RESOURCE_CONFLICT"),
    // Validation
    VALIDATION_FAILED("VALIDATION_FAILED"),
    INVALID_INPUT("INVALID_INPUT"),
    MISSING_REQUIRED_FIELD("MISSING_REQUIRED_FIELD"),
    // Generic
    BUSINESS_ERROR("BUSINESS_ERROR"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    AUTHENTICATION_FAILED("AUTHENTICATION_FAILED"),

    // USER MODULE
    // NotFound
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_VERIFICATION_TOKEN_NOT_FOUND("USER_VERIFICATION_TOKEN_NOT_FOUND"),
    // Conflict
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
    USER_EMAIL_ALREADY_EXISTS("USER_EMAIL_ALREADY_EXISTS"),
    USER_ALREADY_VERIFIED("USER_ALREADY_VERIFIED"),
    // Validation
    USER_SAME_PASSWORD("USER_SAME_PASSWORD"),
    USER_VERIFICATION_TOKEN_INVALID("USER_VERIFICATION_TOKEN_INVALID"),
    USER_VERIFICATION_TOKEN_ALREADY_USED("USER_VERIFICATION_TOKEN_ALREADY_USED"),
    // Unauthorized
    USER_INVALID_CREDENTIALS("USER_INVALID_CREDENTIALS"), // will not map to 403 Unauthorized
    USER_VERIFICATION_TOKEN_EXPIRED("USER_VERIFICATION_TOKEN_EXPIRED"),
    USER_CREDENTIALS_EXPIRED("USER_CREDENTIALS_EXPIRED"),
    // Forbidden
    USER_ACCOUNT_EXPIRED("USER_ACCOUNT_EXPIRED"),
    USER_ACCOUNT_DISABLED("USER_ACCOUNT_DISABLED"),
    USER_ACCOUNT_SUSPENDED("USER_ACCOUNT_SUSPENDED"), // isAccountNonLocked == false

    // AUTH MODULE
    // Validation
    AUTH_TOKEN_MALFORMED("AUTH_TOKEN_MALFORMED"),
    // Unauthorized
    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS"),
    AUTH_TOKEN_INVALID("AUTH_TOKEN_INVALID"),
    AUTH_TOKEN_SIGNATURE_INVALID("AUTH_TOKEN_INVALID"),
    AUTH_TOKEN_EXPIRED("AUTH_TOKEN_EXPIRED"),
    AUTH_REFRESH_TOKEN_NOT_FOUND("AUTH_REFRESH_TOKEN_NOT_FOUND"),
    AUTH_REFRESH_TOKEN_INVALID("AUTH_REFRESH_TOKEN_INVALID"),
    AUTH_REFRESH_TOKEN_REVOKED("AUTH_REFRESH_TOKEN_REVOKED"),
    AUTH_REFRESH_TOKEN_EXPIRED("AUTH_REFRESH_TOKEN_EXPIRED"),
    // Forbidden
    AUTH_FORBIDDEN("AUTH_FORBIDDEN");

    private final String value;
}