package com.notif.api.core.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCodes {
    // Generic, any entity
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    BUSINESS_ERROR("BUSINESS_ERROR"),
    INTEGRATION_ERROR("INTEGRATION_ERROR"),
    INTERNAL_ERROR("INTERNAL_ERROR"),
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),
    NOT_FOUND("NOT_FOUND"),
    ALREADY_EXISTS("ALREADY_EXISTS"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    UNAUTHORIZED("UNAUTHORIZED"),

    // Auth
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    ACCOUNT_DISABLED("ACCOUNT_DISABLED"),
    ACCOUNT_LOCKED("ACCOUNT_LOCKED"),
    PASSWORD_EXPIRED("PASSWORD_EXPIRED"),
    AUTHENTICATION_FAILED("AUTHENTICATION_FAILED"),

    // User
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
    INVALID_TOKEN("INVALID_TOKEN"),
    TOKEN_EXPIRED("TOKEN_EXPIRED"),
    TOKEN_NOT_FOUND("TOKEN_NOT_FOUND"),

    // Validation
    NO_FIELDS_TO_UPDATE("NO_FIELDS_TO_UPDATE");

    private final String value;
}